version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.9
    executor: python/default
    steps:
      - checkout
      - python/load-cache
#       - run:
#           command: pip install -r requirements.txt
#           name: Install Deps
      - python/save-cache
      
  deploy:
    machine:
        enabled: true
    steps:
        - add_ssh_keys:
            fingerprints:
              - "89:3e:81:a9:a9:81:89:2e:19:bb:e3:d2:d0:21:d3:1b"
        - run:
            name: Deploy Over SSH
            command: |
              ssh $SSH_USER@$SSH_HOST "ls && git pull"
workflows:
  main:
    jobs:
      - build
      - deploy
