version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.9
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: pip install -r requirements.txt
          name: Install Deps
      - python/save-cache
      
  deploy:
    machine:
        enabled: true
    steps:
        - add_ssh_keys:
            fingerprints:
              - "23:78:f0:58:dc:e8:89:23:a5:7e:d3:89:bd:bb:a6:6e"
        - run:
            name: Deploy Over SSH
            command: |
              ssh $SSH_USER@$SSH_HOST
              DIRECTORY=/home/ubuntu/chatbot-bocah-alam
              if [ ! -d "$DIRECTORY" ]; then
                echo "Cloning...."
                git clone https://github.com/fendiirfan/chatbot-bocah-alam.git
                echo "===================== Clone successfully ====================="
              fi
              echo ls
              pipenv run pip3 install -r $DIRECTORY/requirements.txt
              echo "Install Depedencies successfully"
              pipenv run streamlit run $DIRECTORY/app.py
              
workflows:
  main:
    jobs:
        - build
        - deploy:
            requires:
              - build

       
