version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.9
    executor: python/default
    steps:
      - checkout
      - python/load-cache
#       - run:
#           command: pip install -r requirements.txt
#           name: Install Deps
      - python/save-cache
      
  deploy:
    machine:
        enabled: true
    steps:
        - add_ssh_keys:
            fingerprints:
              - "9d:e9:41:c0:c2:ff:7c:68:f9:c2:4b:87:49:b9:a4:36"
        - run:
            name: Deploy Over SSH
            command: |
              ssh $SSH_USER@$SSH_HOST "ls && git pull"
workflows:
  main:
    jobs:
      - build
      - deploy
