version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.9
    executor: python/default
    steps:
      - checkout
      - python/load-cache
#       - run:
#           command: pip install -r requirements.txt
#           name: Install Deps
      - python/save-cache
      
  deploy:
    machine:
        enabled: true
    steps:
#         - add_ssh_keys:
#             fingerprints:
#               - "23:78:f0:58:dc:e8:89:23:a5:7e:d3:89:bd:bb:a6:6e"
        - run:
            name: Deploy Over SSH
            command: |
              ssh $SSH_USER@$SSH_HOST "git clone https://github.com/fendiirfan/chatbot-bocah-alam.git && ls"
              
workflows:
    build-and-deploy:
    jobs:
        - build
        - deploy:
            requires:
            - build # only deploy once build job has completed
            filters:
            branches:
                only: main # only deploy on the main branch
