version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-deploy:
    docker:
      - image: circleci/python:3.7.9
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: pip install -r requirements.txt
          name: Install Deps
      - python/save-cache
#       - add_ssh_keys:
#           fingerprints:
#             - "ec:28:a7:28:95:db:e6:78:d3:80:ef:0b:2c:fd:34:8f"
      - run:
          name: Connect to VM
          command: |
           echo "Host my-vm" >> ~/.ssh/config
            echo "  HostName ec2-34-227-56-17.compute-1.amazonaws.com " >> ~/.ssh/config
            echo "  User ubuntu" >> ~/.ssh/config
            echo "  IdentityFile ~/.ssh/my-vm-key" >> ~/.ssh/config
            echo "$SSH_KEY" > ~/.ssh/my-vm-key
            chmod 600 ~/.ssh/my-vm-key
            ssh my-vm -y "ls"
          environment:
            SSH_KEY: |
              $SSH_PRIVATE
          setup_remote_docker:
            host: my-vm
workflows:
  main:
    jobs:
      - build-deploy
