# name: cd

# on:
#   push:
#     branches: [ main ] 

# jobs:
#   build:
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Deploy using ssh
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           key: ${{ secrets.PRIVATE_KEY }}
#           port: 22
#           script: |
#             DIRECTORY=/home/ubuntu/chatbot-bocah-alam
#             if [ ! -d "$DIRECTORY" ]; then
#               echo "Cloning...."
#               git clone https://github.com/fendiirfan/chatbot-bocah-alam.git
#               echo "===================== Clone successfully ====================="
#             fi
#             echo ls
#             pipenv run pip3 install -r $DIRECTORY/requirements.txt
#             echo "Install Depedencies successfully"
#             pipenv run streamlit run $DIRECTORY/app.py

name: Repository Update and Create Folder Example

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run a command
      run: echo "Repository was updated!"
    - name: Create new folder
      run: |
        DIRECTORY=/home/ubuntu/chatbot-bocah-alam
        cd /home/ubuntu
        if [ ! -d "$DIRECTORY" ]; then
          echo "Cloning...."
          git clone https://github.com/fendiirfan/chatbot-bocah-alam.git
          echo "===================== Clone successfully ====================="
        fi
        git clone https://github.com/fendiirfan/chatbot-bocah-alam.git
        echo ls
