name: cd

on:
  push:
    branches: [ main ] 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            DIRECTORY=/home/ubuntu/chatbot-bocah-alam
            if [ ! -d "$DIRECTORY" ]; then
              echo "Cloning...."
              git clone https://github.com/fendiirfan/chatbot-bocah-alam.git
            fi
            echo ls
            pipenv shell
            cd $DIRECTORY
            pip3 install -r requirements.txt
            echo "Install Depedencies successfully"
            streamlit run app.py
